packages:
  - app/*
  - feature/*/**
  - infrastructure/*/**
  - packages/*

catalog:
  typescript: ^7.0.2
  "@nestjs/common": ^12.0.3
  "@nestjs/core": ^12.0.3
  "@nestjs/config": ^12.0.0
  "@nestjs/platform-fastify": ^12.0.3
  fastify: 5.12.5
  "@fastify/multipart": 10.1.1
  zod: ^4.6.5
  '@casl/ability': ^7.0.1

overrides:
  fastify: "catalog:"

allowBuilds:
  "@prisma/engines": true
  "@scarf/scarf": true
  bcrypt: true
  msgpackr-extract: true
  prisma: true
  unrs-resolver: true

# httpsProxy: "http://192.168.1.10:18888"
# httpProxy: "http://192.168.1.10:18888"

fetchTimeout: 90000

minimumReleaseAgeExclude:
  - "@jonoob-part/contracts@1.0.0 || 1.0.1 || 1.0.2"

# registries:
#   default: https://package-mirror.liara.ir/repository/npm/

# strictSsl: false
