packages:
  - app/*
  - feature/*/**
  - infrastructure/*/**
allowBuilds:
  "@prisma/engines": true
  msgpackr-extract: true
  prisma: true
  unrs-resolver: true

# httpsProxy: "http://192.168.1.10:18888"
# httpProxy: "http://192.168.1.10:18888"

fetchTimeout: 90000

# registries:
#   default: https://package-mirror.liara.ir/repository/npm/

# strictSsl: false
