packages:
  - app/*
  - feature/*/**
  - infrastructure/*/**
  - packages/*

catalog:
  typescript: ^7.0.2

allowBuilds:
  "@prisma/engines": true
  msgpackr-extract: true
  prisma: true
  unrs-resolver: true

# httpsProxy: "http://192.168.1.10:18888"
# httpProxy: "http://192.168.1.10:18888"

fetchTimeout: 90000

minimumReleaseAgeExclude:
  - '@jonoob-part/contracts@1.0.0 || 1.0.1 || 1.0.2'

# registries:
#   default: https://package-mirror.liara.ir/repository/npm/

# strictSsl: false
