import { RawProduct } from '@feature/common';
import { ImageRef } from '@feature/media-api';

export type SpecificationReferences = {
  manufacturerId?: string; // This is a reference to brand too, ex: Ezam(brand) -> SazePoyesh(brand)[manufacture]
  brandId?: string;
  categoryIds: string[]; // (taxonomy) `CategoryNode` referenced
  fitmentIds: string[];
};

export type ProductQuality = 'oe' | 'oem' | 'aftermarket';

export type Product = RawProduct & {
  id: string;

  /**
   * This flag is used for separate products that are able to be found in online store
   */
  storefront?: true | false;

  /**
   * This is generated by system technically consist of:
   *  [part of canonicalName, emplacement, fitment['model'], brandName]
   */
  displayName: string;
  canonicalName: string; // model-[...variants], we do not doing search base on this

  // [TODO] Add constraint to ensure product images only accept valid image MIME types.
  // Allowed MIME types should be restricted to image formats (e.g. image/jpeg, image/png, image/webp).
  images: ImageRef[];

  /**
   * Human-defined alternative names.
   * Used as semantic synonyms.
   */
  aliases: string[];
  /**
   * generated by system
   * [canonicalName + aliases + brandName + fitment[model + series + fuelType + transmission]]
   * for improving searching performance
   * [TODO] this can be removed and appear only in db model and generated in lower layer
   */
  searchText: string;

  emplacement?: string;
  quality?: ProductQuality;

  description?: {
    format: 'mdx';
    content: string;
  };

  references: SpecificationReferences;
};
