import { LineItems, UnitOfMeasure } from "@feature/common";

export type CategoryNode = {
  id: string;
  parentId?: string;
  displayValue: string;
};

export type ProductDefinition = {
  enriched?: {
    price: {
      value: number;
      unit: "toman" | "rial";
    };
    stock: number;
    unitOfMeasure?: UnitOfMeasure;
  };
  populated?: {
    displayName: string; // this is generated base on technical
    canonicalName: string; // model-[...variants], we do not doing search base on this
    aliases: string[]; // synonyms
    searchText: string[]; // generated by system for improving search in elasticsearch
    brandId: string;
    categoryIds: string[]; // `CategoryNode` referenced
    fitment;
    emplacement;
  };
};

export type ProductBase = {
  id: string;
  definition: ProductDefinition;
};

export type Product = ProductBase & {
  goodId: string;
  kind: "leaf";
};

export type ProductBundle = ProductBase & {
  id: string;
  kind: "bundle";
  items: LineItems<BundleItem>;
};

export type BundleItem = {
  product: Product;
  quantity: number;
};
